#!/bin/sh
#SBATCH --job-name=zall_admix
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=5G
#SBATCH --time=48:00:00
#SBATCH --account=g102-2488
#SBATCH --partition=okeanos
#SBATCH --output=/home/jl430796/MaizePop/logs/maize_pop.%A_%a.out
#SBATCH --error=/home/jl430796/MaizePop/logs/maize_pop.%A_%a.err

admixture /home/jl430796/MaizePop/data/processed/zea_all/chr_zea_all_plink_3.bed 5
